<a href="https://colab.research.google.com/github/Allanjs1/python.unopar/blob/main/Untitled1_ipynb2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import pandas as pd
df_selic = pd.read_json("https://api.bcb.gov.br/dados/serie/bcdata.sgs.11/dados?formato=json")

print(df_selic.info())
print(df_selic)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9616 entries, 0 to 9615
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   data    9616 non-null   object
 1   valor   9616 non-null   float64
dtypes: float64(1), object(1)
memory usage: 150.4+ KB
None
            data     valor
0     04/06/1986  0.065041
1     05/06/1986  0.067397
2     06/06/1986  0.066740
3     09/06/1986  0.068247
4     10/06/1986  0.067041
...          ...       ...
9611  04/10/2024  0.040168
9612  07/10/2024  0.040168
9613  08/10/2024  0.040168
9614  09/10/2024  0.040168
9615  10/10/2024  0.040168

[9616 rows x 2 columns]

In [10]:
df_selic.drop_duplicates(keep='last', inplace=True)

In [11]:
print(df_selic)

            data     valor
0     04/06/1986  0.065041
1     05/06/1986  0.067397
2     06/06/1986  0.066740
3     09/06/1986  0.068247
4     10/06/1986  0.067041
...          ...       ...
9611  04/10/2024  0.040168
9612  07/10/2024  0.040168
9613  08/10/2024  0.040168
9614  09/10/2024  0.040168
9615  10/10/2024  0.040168

[9616 rows x 2 columns]

In [15]:
from datetime import date

from datetime import datetime as dt



data_extracao = date.today()



df_selic['data_extracao'] = data_extracao
df_selic['responsavel'] = "Autor"



print(df_selic.info())
df_selic.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9616 entries, 0 to 9615
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   data           9616 non-null   object
 1   valor          9616 non-null   float64
 2   data_extracao  9616 non-null   object
 3   responsavel    9616 non-null   object
dtypes: float64(1), object(3)
memory usage: 300.6+ KB
None

         data     valor data_extracao responsavel
0  04/06/1986  0.065041    2024-10-10       Autor
1  05/06/1986  0.067397    2024-10-10       Autor
2  06/06/1986  0.066740    2024-10-10       Autor
3  09/06/1986  0.068247    2024-10-10       Autor
4  10/06/1986  0.067041    2024-10-10       Autor
5  11/06/1986  0.066740    2024-10-10       Autor
6  12/06/1986  0.066575    2024-10-10       Autor
7  13/06/1986  0.066164    2024-10-10       Autor
8  16/06/1986  0.066493    2024-10-10       Autor
9  17/06/1986  0.066247    2024-10-10       Autor

In [22]:
df_selic.loc[9389]

data             20/11/2023
valor              0.045513
data_extracao    2024-10-10
responsavel           Autor
Name: 9389, dtype: object

In [23]:
df_selic.loc[[10,20,40,50]]

          data     valor data_extracao responsavel
10  18/06/1986  0.066301    2024-10-10       Autor
20  02/07/1986  0.068301    2024-10-10       Autor
40  30/07/1986  0.088795    2024-10-10       Autor
50  13/08/1986  0.129315    2024-10-10       Autor

In [24]:
teste = df_selic['valor'] < 0.01
print(type(teste))

<class 'pandas.core.series.Series'>

In [25]:
print(teste)

0       False
1       False
2       False
3       False
4       False
        ...
9611    False
9612    False
9613    False
9614    False
9615    False
Name: valor, Length: 9616, dtype: bool

In [30]:
import pandas as pd


# Criando um DataFrame com 5 linhas de dados

data = {

    'nome': ['Produto A', 'Produto B', 'Produto C', 'Produto A', 'Produto E'],

    'quantidade de itens comprados': [3, 1, 4, 3, 2],

    'tipo de item': ['Eletrônico', 'Vestuário', 'Alimento', 'Eletrônico', 'Alimento'],

    'receita total': [120, 80, 60, 120, 90]

}

df = pd.DataFrame(data)
print(df)

        nome  quantidade de itens comprados tipo de item  receita total
0  Produto A                              3   Eletrônico            120
1  Produto B                              1    Vestuário             80
2  Produto C                              4     Alimento             60
3  Produto A                              3   Eletrônico            120
4  Produto E                              2     Alimento             90

In [32]:
# Duplicando uma linha

df.drop_duplicates(keep='last', inplace=True)
print(df)

        nome  quantidade de itens comprados tipo de item  receita total
1  Produto B                              1    Vestuário             80
2  Produto C                              4     Alimento             60
3  Produto A                              3   Eletrônico            120
4  Produto E                              2     Alimento             90

In [ ]:
# Calculando a coluna 'preço do item'

df['preço do item'] = df['receita total'] / df['quantidade de itens comprados']


# Selecionando preço do item acima de 50 reais
itens_acima_de_50 = df[df['preço do item'] > 50]


print"Ítens acima de 50 reais:")
print(itens_acima_de_50)

In [41]:

# Calculando a coluna 'preço do item'

df['preço do item'] = df['receita total'] / df['quantidade de itens comprados']



# Selecionando preço do item acima de 50 reais

itens_acima_de_50 = df[df['preço do item'] > 50]


print("Itens acima de 50 reais:")
print(itens_acima_de_50)

Itens acima de 50 reais:
        nome  quantidade de itens comprados tipo de item  receita total  \
1  Produto B                              1    Vestuário             80

   preço do item
1           80.0